FROM ghcr.io/allenai/pytorch:2.4.0-cuda12.1-python3.11
ENV CUDA_HOME=/opt/conda

WORKDIR /root

# Disable welcome messages
RUN chmod -x /etc/update-motd.d/* && touch /etc/hushlogin

# Install apt packages
RUN apt-get update && apt-get install -y \
    openssh-server \
    figlet \
    lolcat \
    tree \
    && apt-get clean

# Configure OpenSSH (allow external connections, port 8080)
RUN mkdir -p /run/sshd && chmod 755 /run/sshd && \
    sed -i 's/^#PubkeyAuthentication/PubkeyAuthentication/; s/^#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config
RUN sed -i 's/#Port 22/Port 8080/' /etc/ssh/sshd_config

# Add SSH pubkeys
COPY .ssh/authorized_keys /root/.ssh/authorized_keys

# Add .gitconfig
COPY .gitconfig /root/.gitconfig

# Add .bashrc
COPY .bashrc /root/.bashrc
RUN chmod 644 /root/.bashrc

# Add custom commands (like ChatGPT!)
RUN mkdir -p /root/bin
COPY bin/ /root/bin/

# COPY requirements_beaker.txt .

# # Run core requirements here
# RUN pip install -r requirements_beaker.txt  && pip cache purge
# RUN python -m nltk.downloader punkt

# # Custom installation for vllm (0.6.2 actually installs pytorch 2.4.1)
# RUN pip install "vllm>=0.6.2,<0.6.4" && pip cache purge
# RUN pip install xformers && pip cache purge

# # Install latest ai2-olmo from github 
# RUN pip install git+https://github.com/allenai/OLMo.git@main && pip cache purge

# ARG GIT_REF=""
# ENV GIT_REF=${GIT_REF}

# # Install Jupyter Notebook
# RUN pip install notebook

# Expose OpenSSH and Jupyter ports
EXPOSE 8080 8888