name: Build ai2/davidh-interactive

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    # Run this workflow anytime anytime these paths update 
    # (+ anytime there's a new release tag for this image)
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.github/workflows'
    branches:
      - main
  workflow_dispatch:  # allow manual triggers on GitHub UI
    inputs:
      run_build:
        description: 'Run build job'
        type: boolean
        default: true
      run_test_clusters:
        description: 'Run test clusters job'
        type: boolean
        default: true

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    name: davidh_image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: (github.event_name != 'workflow_run' && (github.event_name != 'workflow_dispatch' || inputs.run_build)) || (github.event.workflow_run.conclusion == 'success')
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          beaker_token: ${{ secrets.BEAKER_TOKEN }}

      - name: Delete huge unnecessary tools folder # helps with big images
        run: rm -rf /opt/hostedtoolcache

      - name: Build image
        run: |
          docker buildx build \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --build-arg GIT_REF=$(git rev-parse HEAD) \
              -f Dockerfile \
              -t davidh_image \
              .

      - name: Push image
        uses: ./.github/actions/push
        with:
          image: davidh_image  # tag of the image we just built in the previous step
          beaker: davidh-interactive  # name of the image on Beaker
          latest: true  # label this image as the 'latest'

      - name: Test image
        uses: ./.github/actions/test
        with:
          beaker: davidh-interactive  # name of the image on Beaker

  test-clusters:
    runs-on: ubuntu-latest-large
    needs: build
    if: github.event_name != 'workflow_dispatch' || inputs.run_test_clusters
    strategy:
      matrix:
        cluster: [
          'ai2/jupiter-cirrascale-2',
          'ai2/saturn-cirrascale',
          'ai2/titan-cirrascale',
          'ai2/neptune-cirrascale',
          'ai2/ceres-cirrascale',
          'ai2/phobos-cirrascale',
          'ai2/triton-cirrascale'
        ]
      fail-fast: false # Allow other clusters to continue even if one fails
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          beaker_token: ${{ secrets.BEAKER_TOKEN }}
      
      - name: Test Beaker container
        uses: ./.github/actions/test
        with:
          beaker: davidh-interactive
          cluster: ${{ matrix.cluster }}

